### ISSUE TITLE
Clojure sets do not round-trip as expected

### ISSUE THREAD

**Issue by rschmitt** [clojure/data.fressian#5] opened 2015-03-15 23:41 UTC
Sets get read back as a java.util.HashSet instead of a clojure.lang.PersistentHashSet:

``` clojure
user=> (-> {} fress/write fress/read class)
clojure.lang.PersistentArrayMap
user=> (-> #{} fress/write fress/read class)
java.util.HashSet
```

I realize that "list" is a special case within Fressian (user handlers get bypassed, even if they implement the ConvertList interface), but that doesn't appear to be the case with sets. Sets, like maps, are implemented like any other struct in Fressian, and data.fressian could supply a user handler that returns a PersistentHashSet.

**Comment by rschmitt** [comment] 2015-03-15 23:50
Looks like this is a [known issue](http://dev.clojure.org/jira/browse/DFRS-5).

**Comment by jafingerhut** [comment] 2015-03-16 01:20
Clojure contrib libraries use JIRA for ticket tracking, not Github issues.  I'd recommend voting on the JIRA ticket, and adding a comment to it if you have anything to add to the description that is not already there.

**Comment by stuarthalloway** [comment] 2017-08-09 20:19
This is a duplicate of https://dev.clojure.org/jira/browse/DFRS-5

**Closed by stuarthalloway** 2017-08-09 20:19 UTC
